baseURL = 'https://www.joys-corner.com/'
languageCode = 'en-us'
title = "Joy's Corner"
theme = 'nostyleplease'

[params]
    author = "Joy"
    description = "A minimalist space for my thoughts."
    # Most themes use 'accent' - let's try both to be safe
    accent = "#ff5e62"
    themeColor = "#ff5e62"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2